-- Jalankan SEKALI di phpMyAdmin untuk database Minami yang SUDAH TERPASANG.
-- Jika database baru dibuat dari api/schema.sql, file ini TIDAK perlu dijalankan.
-- Setelah migrasi ini, API tidak mengubah struktur tabel saat runtime.

ALTER TABLE player_global_stats
  ADD COLUMN tenho INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN pots INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN cards INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN jokers INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN best_combo INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN dead INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN mvp INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN best_streak INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE player_mode_stats
  ADD COLUMN tenho INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN pots INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN cards INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN jokers INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN best_combo INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN dead INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN mvp INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN best_streak INT UNSIGNED NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS player_stat_events (
  user_id BIGINT UNSIGNED NOT NULL,
  event_id VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id,event_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
