CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_global_stats (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  games_finished INT UNSIGNED NOT NULL DEFAULT 0,
  game_wins INT UNSIGNED NOT NULL DEFAULT 0,
  rank1 INT UNSIGNED NOT NULL DEFAULT 0,
  match_finished INT UNSIGNED NOT NULL DEFAULT 0,
  match_wins INT UNSIGNED NOT NULL DEFAULT 0,
  tenho INT UNSIGNED NOT NULL DEFAULT 0,
  pots INT UNSIGNED NOT NULL DEFAULT 0,
  cards INT UNSIGNED NOT NULL DEFAULT 0,
  jokers INT UNSIGNED NOT NULL DEFAULT 0,
  best_combo INT UNSIGNED NOT NULL DEFAULT 0,
  dead INT UNSIGNED NOT NULL DEFAULT 0,
  mvp INT UNSIGNED NOT NULL DEFAULT 0,
  best_streak INT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_mode_stats (
  user_id BIGINT UNSIGNED NOT NULL,
  mode VARCHAR(16) NOT NULL,
  games_finished INT UNSIGNED NOT NULL DEFAULT 0,
  game_wins INT UNSIGNED NOT NULL DEFAULT 0,
  rank1 INT UNSIGNED NOT NULL DEFAULT 0,
  match_finished INT UNSIGNED NOT NULL DEFAULT 0,
  match_wins INT UNSIGNED NOT NULL DEFAULT 0,
  tenho INT UNSIGNED NOT NULL DEFAULT 0,
  pots INT UNSIGNED NOT NULL DEFAULT 0,
  cards INT UNSIGNED NOT NULL DEFAULT 0,
  jokers INT UNSIGNED NOT NULL DEFAULT 0,
  best_combo INT UNSIGNED NOT NULL DEFAULT 0,
  dead INT UNSIGNED NOT NULL DEFAULT 0,
  mvp INT UNSIGNED NOT NULL DEFAULT 0,
  best_streak INT UNSIGNED NOT NULL DEFAULT 0,
  joker_sets INT UNSIGNED NOT NULL DEFAULT 0,
  caught INT UNSIGNED NOT NULL DEFAULT 0,
  caught_by INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, mode),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE achievements (
  id VARCHAR(64) PRIMARY KEY,
  mode VARCHAR(16) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_achievements (
  user_id BIGINT UNSIGNED NOT NULL,
  achievement_id VARCHAR(64) NOT NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 1,
  unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, achievement_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE login_sessions (
  token_hash CHAR(64) PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_game_saves (
  user_id BIGINT UNSIGNED NOT NULL,
  mode VARCHAR(16) NOT NULL,
  state_json MEDIUMTEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, mode),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS player_stat_events (
  user_id BIGINT UNSIGNED NOT NULL,
  event_id VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id,event_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS user_profiles (
  user_id BIGINT UNSIGNED NOT NULL,
  profile_id VARCHAR(32) NOT NULL DEFAULT 'cartoon_01',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Progress achievement disimpan terpisah dari status unlock.
CREATE TABLE IF NOT EXISTS user_achievement_progress (
  user_id BIGINT UNSIGNED NOT NULL,
  achievement_code VARCHAR(64) NOT NULL,
  progress INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, achievement_code),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
